# Generated by Django 5.0.7 on 2024-08-03 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('locality', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(default=0)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(choices=[('Madhya Pradesh', 'Madhya Pradesh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Bihar', 'Bihar'), ('Gujrat', 'Gujrat'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Haryana', 'Haryana'), ('Rajasthan', 'Rajasthan'), ('Maharashtra', 'Maharashtra')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
